version: '3.8'
services:
  scraper:
    image: sreality-scraper
    restart: on-failure
    build:
      context: ./scraper
      dockerfile: Dockerfile

  web:
    image: sreality-sell-flats-web
    restart: on-failure
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - 8080:8080

  db:
    image: "postgres:12"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db
    volumes:
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
